version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/osakaturiba
      - public-data:/osakaturiba/public
      - tmp-data:/osakaturiba/tmp
      - log-data:/osakaturiba/log
    depends_on:
      - db
      - chrome

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444

  db:
    image: mysql:8.0.23
    env_file:
      - ./environments/db.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/osakaturiba/public
      - tmp-data:/osakaturiba/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: